export const thrower = exceptionName => {
  throw new exceptionName();
};
